### ISSUE TITLE
Add Markdown processing to page blurbs in generated landing pages

### ISSUE THREAD

**Issue by ryangyoung** [ripple/dactyl#40]
See if there's a way to pass a Markdown-parsing function to the Jinja templates so that template blurbs can include Markdown syntax.

Might require a new Dactyl version or at least a Dactyl filter.

Jira ticket: https://ripplelabs.atlassian.net/browse/DOC-1577

**Comment by mDuo13** [comment]
Recommended alternative is to use a really basic file with some frontmatter for landing pages, and put the Markdown in the page content.
