### ISSUE TITLE
Feature request: make .html extension optional on generated files

### ISSUE THREAD

**Issue by ryangyoung** [ripple/dactyl#42]
People have noted that the `.html` extension on xrpl.org pages gives the impression that we are somewhat behind the times. Other comparable sites don't use such extensions and thus their use may reflect poorly on sites powered by Dactyl. 

Here are some of the competitive examples:

* https://stripe.com/docs/stripe-js/elements/payment-request-button
* https://0x.org/wiki#Get-Started-With-Instant
* https://developers.libra.org/docs/my-first-transaction
* https://ethereum.org/use/#_1-use-an-application-built-on-ethereum

**Comment by iroskam** [comment]
This is typically achieved by rewrite rules on the server.

**Comment by mDuo13** [comment]
What iroskam said. Also, you can, if you need, use whatever output file names you want, but you might end up having to worry about the MIME types / content types being wrong if you don't have correct file extensions.

**Comment by mDuo13** [comment]
An alternative option that may help with this is to improve built-in Dactyl support for using such rules with a Dactyl-generated site.

For example, a built-in server (#47) could optionally support it, and a Dactyl starter kit could come with suggested rewrite rules to apply to your webserver for the same purposes.

The Dactyl link checker could also use some improvements to better handle absolute links and links with the `.html` suffix dropped on the web-server side.

**Comment by mDuo13** [comment]
Fixed in v0.10.0
